version: "3.8"

services:
  microvault:
    image: microvault:latest
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    privileged: True
    volumes:
      - .:/microvault
    environment:
      - DISPLAY=:9
    command:
      - /bin/bash
      - -c
      - |
        cd /microvault && ls && pwd

  environment:
    extends: microvault
    command: python3 /microvault/microvault/environment/continuous.py

  test:
    extends: microvault
    command: poetry run task test
